source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'
gem "active_model_serializers", github: "rails-api/active_model_serializers"
gem 'rack-cors', :require => 'rack/cors'
# gem 'active-model-adapter-source'
gem "refile", require: "refile/rails"
gem "refile-mini_magick"

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails', '~> 3.0'
end

group :development do
  gem 'guard-rspec', require: false
  gem 'guard'
  gem 'guard-bundler', require: false
end

group :test do
  gem 'shoulda-matchers', require: false
end
